version: '3'
services:
  ofoody:
    build: .
    ports:
      - "9999:9999"
  mysql:
    image: "mysql:8.0"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ofoody
      MYSQL_USER: ofoody
      MYSQL_PASSWORD: ofoody
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
